import { DIFFICULTY_INDICATORS } from './constants.js';

export const getInitialTemplate = (rawPrompt) => `
You are an expert prompt engineer specializing in PE² (Prompt Engineering 2.0) optimization.

Transform the following raw prompt into a structured PE² format with exactly these 5 sections:

Raw prompt to optimize:
---
${rawPrompt}
---

Return ONLY a valid JSON object with these exact keys:
{
  "context": "Comprehensive problem description and scope",
  "role": "Expert persona for the LLM to adopt",
  "task": "Step-by-step breakdown of required actions",
  "constraints": "Rules, limitations, and boundaries",
  "output": "Expected format and structure of the response"
}

CRITICAL: Return ONLY the JSON object. No explanations or additional text.
`;

export const getRefinementTemplate = (currentPromptJson, iterationNum) => `
You are refining a PE² prompt for iteration ${iterationNum}.

Current PE² Prompt:
${currentPromptJson}

Analyze and improve the prompt by:
1. Enhancing clarity and specificity
2. Ensuring all PE² sections are well-balanced
3. Optimizing for better LLM performance
4. Maintaining logical consistency
5. Improving actionability

Return ONLY the improved JSON object with the same 5 sections.
`;

function buildMetadataHeader(indicator, difficulty, complexityScore) {
    const timestamp = new Date().toLocaleString();
    return `# PE²-Optimized Prompt ${indicator}\n\n**Difficulty Level:** ${difficulty} | **Complexity Score:** ${complexityScore}/20 | **Generated:** ${timestamp}`;
}

function buildPromptSections(pe2Prompt) {
    const sections = ['Context', 'Role', 'Task', 'Constraints', 'Output'];
    return sections.map(section => {
        const key = section.toLowerCase();
        return `## ${section}\n${pe2Prompt[key] || 'N/A'}`;
    }).join('\n\n');
}

function buildRefinementHistory(history) {
    const entries = history.map(item => `### Iteration ${item.iteration}\n- ${item.edits}`);
    return `# Refinement History\n${entries.join('\n\n')}`;
}

function buildPerformanceSection(metrics, difficulty, complexityScore, historyLength) {
    return `# Performance Metrics
- **Estimated Accuracy Gain**: ${metrics.accuracy_gain || 'N/A'}
- **Complexity Analysis**: ${difficulty} level prompt with ${complexityScore}/20 complexity score
- **Optimization Level**: ${historyLength} iterations applied
- **Generated by**: KleoSr PE²-CLI`;
}

export function formatMarkdownOutput(formatOptions) {
    const { pe2Prompt, history, metrics, difficulty, complexityScore } = formatOptions;
    const indicator = DIFFICULTY_INDICATORS[difficulty];

    const header = buildMetadataHeader(indicator, difficulty, complexityScore);
    const analysis = `## Agentic Analysis\n- **Optimization Level:** ${metrics.optimization_level || 'N/A'}\n- **Overall Quality:** ${metrics.quality_score || 'N/A'}`;
    const sections = buildPromptSections(pe2Prompt);
    const historySection = buildRefinementHistory(history);
    const performance = buildPerformanceSection(metrics, difficulty, complexityScore, history.length);

    return `${header}\n\n${analysis}\n\n${sections}\n\n---\n\n${historySection}\n\n---\n\n${performance}\n\n---\n\n*Generated by KleoSr PE²-CLI*\n`;
}
